### ISSUE TITLE
Support for dictionaries to supply action data

### ISSUE THREAD

**Issue by andresberrios** [tokenika/eosfactory#38]
I don't see why the action data should be specified as a JSON string. It would be much nicer to write if the data parameters for pushing actions would be python dicts that simply get converted to JSON internally before sending to cleos. Of course directly writing JSON strings would still be supported.

What do you think?

**Comment by jakub-zarembinski** [comment]
Thank you for your message - it has prompted us to improve our code.

The problem is that EOSIO has a specific requirement regarding the JSON standard: in EOSIO the order of parameters **does** matter (even though they are named). Hence, using Python dicts becomes problematic, as JSON does not care about ordering.

But we agree with your suggestion: our current implementation is a bit awkward.

So we'll be changing it in the coming release.

Instead of the current syntax looking like this:
```
account_tic_tac_toe.push_action(
    "create", 
    '{"challenger":"' + str(account_alice) 
        +'", "host":"' + str(account_carol) + '"}',
    account_carol)
```
... we'll be introducing something like this:
```
account_tic_tac_toe.push_action(
    "create", 
    '''{
        "challenger": "account_alice",
        "host": "account_carol"
    }''',
    account_carol)
```
